on: push
name: Integrate
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.14", "1.13"]
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go build ./...

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.14", "1.13"]
    name: Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go test ./...
