on: push
name: Integrate
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: 1.12.8
    - run: go build ./...

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: 1.12.8
    - run: go test ./...
